development:
  adapter: postgresql
  encoding: UTF8
  database: <%= ENV["DATABASE_NAME"] %>
  pool: 50
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: UTF8
  database: scanner_test
  pool: 5

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  reaping_frequency: <%= ENV["DB_REAPING_FREQUENCY"] || 60 %>
